server:
  port: 8090

spring:
  application:
    name: spring-gateway
  cloud:
    gateway:
      routes:
      - id: BookModule
        uri: lb://book-service
        predicates:
        - Path=/api/v1/books/**
      - id: OrderModule
        uri: lb://order-service
        predicates:
        - Path=/api/v1/orders/**
      - id: CustomerModule
        uri: lb://customer-service
        predicates:
        - Path=/api/v1/customers/**
        
        
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
